using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System.IO;
using Random = UnityEngine.Random;

public class Items : MonoBehaviour 
{
    public Text displayText;
    string[] item = new string[]
    {
    "Acacia Boat",
    "Acacia Boat with Chest",
    "Acacia Button",
    "Acacia Door",
    "Acacia Fence",
    "Acacia Fence Gate",
    "Acacia Hanging Sign",
    "Acacia Leaves",
    "Acacia Log",
    "Acacia Planks",
    "Acacia Pressure Plate",
    "Acacia Sapling",
    "Acacia Sign",
    "Acacia Slab",
    "Acacia Stairs",
    "Acacia Trapdoor",
    "Acacia Wood",
    "Activator Rail",
    "Allium",
    "Amethyst Cluster",
    "Amethyst Shard",
    "Ancient Debris",
    "Andesite",
    "Andesite Slab",
    "Andesite Stairs",
    "Andesite Wall",
    "Anvil",
    "Apple",
    "Armadillo Scute",
    "Armor Stand",
    "Arrow",
    "Arrow of Fire Resistance",
    "Arrow of Fire Resistance +",
    "Arrow of Harming",
    "Arrow of Harming II",
    "Arrow of Healing",
    "Arrow of Healing II",
    "Arrow of Invisibility",
    "Arrow of Invisibility +",
    "Arrow of Leaping",
    "Arrow of Leaping +",
    "Arrow of Leaping II",
    "Arrow of Luck? [JE]",
    "Arrow of Night Vision",
    "Arrow of Night Vision +",
    "Arrow of Poison",
    "Arrow of Poison +",
    "Arrow of Poison II",
    "Arrow of Regeneration",
    "Arrow of Regeneration +",
    "Arrow of Regenration II",
    "Arrow of Slowness",
    "Arrow of Slowness +",
    "Arrow of Slowness IV",
    "Arrow of Splashing",
    "Arrow of Strength",
    "Arrow of Strength +",
    "Arrow of Strength II",
    "Arrow of Swiftness",
    "Arrow of Swiftness +",
    "Arrow of Swiftness II",
    "Arrow of the Turtle Master",
    "Arrow of the Turtle Master +",
    "Arrow of the Turtle Master II",
    "Arrow of Water Breathing",
    "Arrow of Water Breathing +",
    "Arrow of Weakness",
    "Arrow of Weakness +",
    "Azalea",
    "Azalea Leaves",
    "Azure Bluet",
    "Baked Potato",
    "Bamboo",
    "Bamboo Button",
    "Bamboo Door",
    "Bamboo Fence",
    "Bamboo Fence Gate",
    "Bamboo Hanging Sign",
    "Bamboo Mosaic",
    "Bamboo Mosaic Slab",
    "Bamboo Mosaic Stairs",
    "Bamboo Planks",
    "Bamboo Pressure Plate",
    "Bamboo Raft",
    "Bamboo Raft with Chest",
    "Bamboo Sign",
    "Bamboo Slab",
    "Bamboo Stairs",
    "Bamboo Trapdoor",
    "Banner Pattern (Creeper Charge)",
    "Banner Pattern (Flower Charge)",
    "Banner Pattern (Globe)",
    "Banner Pattern (Skull Charge)",
    "Banner Pattern (Snout)",
    "Banner Pattern (Thing)",
    "Barrel",
    "Basalt",
    "Beacon",
    "Bee Nest",
    "Beehive",
    "Beetroot",
    "Beetroot Seeds",
    "Beetroot Soup",
    "Bell",
    "Big Dripleaf",
    "Birch Boat",
    "Birch Boat with Chest",
    "Birch Button",
    "Birch Door",
    "Birch Fence",
    "Birch Fence Gate",
    "Birch Hanging Sign",
    "Birch Leaves",
    "Birch Log",
    "Birch Planks",
    "Birch Pressure Plate",
    "Birch Sapling",
    "Birch Sign",
    "Birch Slab",
    "Birch Stairs",
    "Birch Trapdoor",
    "Birch Wood",
    "Black Banner",
    "Black Bed",
    "Black Candle",
    "Black Carpet",
    "Black Concrete",
    "Black Concrete Powder",
    "Black Dye",
    "Black Glazed Terracotta",
    "Black Shulker Box",
    "Black Stained Glass",
    "Black Stained Glass Pane",
    "Black Terracotta",
    "Black Wool",
    "Blackstone",
    "Blackstone Slab",
    "Blackstone Stairs",
    "Blackstone Wall",
    "Blast Furnace",
    "Blaze Powder",
    "Blaze Rod",
    "Block of Amethyst",
    "Block of Bamboo",
    "Block of Coal",
    "Block of Copper",
    "Block of Diamond",
    "Block of Emerald",
    "Block of Gold",
    "Block of Iron",
    "Block of Lapis Lazuli",
    "Block of Netherite",
    "Block of Quartz",
    "Block of Raw Copper",
    "Block of Raw Gold",
    "Block of Raw Iron",
    "Block of Redstone",
    "Block of Stripped Bamboo",
    "Blue Banner",
    "Blue Bed",
    "Blue Candle",
    "Blue Carpet",
    "Blue Concrete",
    "Blue Concrete Powder",
    "Blue Dye",
    "Blue Glazed Terracotta",
    "Blue Ice",
    "Blue Orchid",
    "Blue Shulker Box",
    "Blue Stained Glass",
    "Blue Stained Glass Pane",
    "Blue Terracotta",
    "Blue Wool",
    "Bone",
    "Bone Block",
    "Bone Meal",
    "Book",
    "Book and Quill",
    "Bookshelf",
    "Bottle o' Enchanting",
    "Bow",
    "Bowl",
    "Brain Coral",
    "Brain Coral Block",
    "Brain Coral Fan",
    "Bread",
    "Brewing Stand",
    "Brick",
    "Brick Slab",
    "Brick Stairs",
    "Brick Wall",
    "Bricks",
    "Brown Banner",
    "Brown Bed",
    "Brown Candle",
    "Brown Carpet",
    "Brown Concrete",
    "Brown Concrete Powder",
    "Brown Dye",
    "Brown Glazed Terracotta",
    "Brown Mushroom",
    "Brown Mushroom Block",
    "Brown Shulker Box",
    "Brown Stained Glass",
    "Brown Stained Glass Pane",
    "Brown Terracotta",
    "Brown Wool",
    "Brush",
    "Bubble Coral",
    "Bubble Coral Block",
    "Bubble Coral Fan",
    "Bucket",
    "Bucket of Axolotl",
    "Bucket of Cod",
    "Bucket of Pufferfish",
    "Bucket of Salmon",
    "Bucket of Tadpole",
    "Bucket of Tropical Fish",
    "Buried Treasure Map ",
    "Cactus",
    "Cake",
    "Calcite",
    "Calibrated Sculk Sensor",
    "Campfire",
    "Candle",
    "Carrot",
    "Carrot on a Stick",
    "Cartography Table",
    "Carved Pumpkin",
    "Cauldron",
    "Chain",
    "Chainmail Boots",
    "Chainmail Chestplate",
    "Chainmail Helmet",
    "Chainmail Leggings",
    "Charcoal",
    "Cherry Boat",
    "Cherry Boat with Chest",
    "Cherry Button",
    "Cherry Door",
    "Cherry Fence",
    "Cherry Fence Gate",
    "Cherry Hanging Sign",
    "Cherry Leaves",
    "Cherry Log",
    "Cherry Planks",
    "Cherry Pressure Plate",
    "Cherry Sapling",
    "Cherry Sign",
    "Cherry Slab",
    "Cherry Stairs",
    "Cherry Trapdoor",
    "Cherry Wood",
    "Chest",
    "Chipped Anvil",
    "Chiseled Bookshelf",
    "Chiseled Deepslate",
    "Chiseled Nether Bricks",
    "Chiseled Polished Blackstone",
    "Chiseled Quartz Block",
    "Chiseled Red Sandstone",
    "Chiseled Sandstone",
    "Chiseled Stone Bricks",
    "Chorus Flower",
    "Chorus Fruit",
    "Clay",
    "Clay Ball",
    "Clock",
    "Coal",
    "Coal Ore",
    "Coarse Dirt",
    "Cobbled Deepslate",
    "Cobbled Deepslate Slab",
    "Cobbled Deepslate Stairs",
    "Cobbled Deepslate Wall",
    "Cobblestone",
    "Cobblestone Slab",
    "Cobblestone Stairs",
    "Cobblestone Wall",
    "Cobweb",
    "Cocoa Beans",
    "Compass",
    "Composter",
    "Conduit",
    "Cooked Chicken",
    "Cooked Cod",
    "Cooked Mutton",
    "Cooked Porkchop",
    "Cooked Rabbit",
    "Cooked Salmon",
    "Cookie",
    "Copper Ingot",
    "Copper Ore",
    "Cornflower",
    "Cracked Deepslate Bricks",
    "Cracked Deepslate Tiles",
    "Cracked Nether Bricks",
    "Cracked Polished Blackstone Bricks",
    "Cracked Stone Bricks",
    "Crafting Table",
    "Creeper Head",
    "Crimson Button",
    "Crimson Door",
    "Crimson Fence",
    "Crimson Fence Gate",
    "Crimson Fungus",
    "Crimson Hanging Sign",
    "Crimson Hyphae",
    "Crimson Nylium",
    "Crimson Planks",
    "Crimson Pressure Plate",
    "Crimson Roots",
    "Crimson Sign",
    "Crimson Slab",
    "Crimson Stairs",
    "Crimson Stem",
    "Crimson Trapdoor",
    "Crossbow",
    "Crying Obsidian",
    "Cut Copper",
    "Cut Copper Slab",
    "Cut Copper Stairs",
    "Cut Red Sandstone",
    "Cut Red Sandstone Slab",
    "Cut Sandstone",
    "Cut Sandstone Slab",
    "Cyan Banner",
    "Cyan Bed",
    "Cyan Candle",
    "Cyan Carpet",
    "Cyan Concrete",
    "Cyan Concrete Powder",
    "Cyan Dye",
    "Cyan Glazed Terracotta",
    "Cyan Shulker Box",
    "Cyan Stained Glass",
    "Cyan Stained Glass Pane",
    "Cyan Terracotta",
    "Cyan Wool",
    "Damaged Anvil",
    "Dandelion",
    "Dark Oak Boat",
    "Dark Oak Boat with Chest",
    "Dark Oak Button",
    "Dark Oak Door",
    "Dark Oak Fence",
    "Dark Oak Fence Gate",
    "Dark Oak Hanging Sign",
    "Dark Oak Leaves",
    "Dark Oak Log",
    "Dark Oak Planks",
    "Dark Oak Pressure Plate",
    "Dark Oak Sapling",
    "Dark Oak Sign",
    "Dark Oak Slab",
    "Dark Oak Stairs",
    "Dark Oak Trapdoor",
    "Dark Oak Wood",
    "Dark Prismarine",
    "Dark Prismarine Slab",
    "Dark Prismarine Stairs",
    "Daylight Detector",
    "Dead Brain Coral",
    "Dead Brain Coral Block",
    "Dead Brain Coral Fan",
    "Dead Bubble Coral",
    "Dead Bubble Coral Block",
    "Dead Bubble Coral Fan",
    "Dead Bush",
    "Dead Fire Coral",
    "Dead Fire Coral Block",
    "Dead Fire Coral Fan",
    "Dead Horn Coral",
    "Dead Horn Coral Block",
    "Dead Horn Coral Fan",
    "Dead Tube Coral",
    "Dead Tube Coral Block",
    "Dead Tube Coral Fan",
    "Deepslate",
    "Deepslate Brick Slab",
    "Deepslate Brick Stairs",
    "Deepslate Brick Wall",
    "Deepslate Bricks",
    "Deepslate Coal Ore",
    "Deepslate Copper Ore",
    "Deepslate Diamond Ore",
    "Deepslate Emerald Ore",
    "Deepslate Gold Ore",
    "Deepslate Iron Ore",
    "Deepslate Lapis Lazuli Ore",
    "Deepslate Redstone Ore",
    "Deepslate Tile Slab",
    "Deepslate Tile Stairs",
    "Deepslate Tile Wall",
    "Deepslate Tiles",
    "Detector Rail",
    "Diamond",
    "Diamond Axe",
    "Diamond Boots",
    "Diamond Chestplate",
    "Diamond Helmet",
    "Diamond Hoe",
    "Diamond Horse Armor",
    "Diamond Leggings",
    "Diamond Ore",
    "Diamond Pickaxe",
    "Diamond Shovel",
    "Diamond Sword",
    "Diorite",
    "Diorite Slab",
    "Diorite Stairs",
    "Diorite Wall",
    "Dirt",
    "Disc Fragment",
    "Dispenser",
    "Dragon Egg",
    "Dragon Head",
    "Dragon's Breath",
    "Dried Kelp",
    "Dried Kelp Block",
    "Dripstone Block",
    "Dropper",
    "Echo Shard",
    "Egg",
    "Elytra",
    "Emerald",
    "Emerald Ore",
    "Empty Map",
    "Enchanted Golden Apple",
    "Enchanting Table",
    "End Crystal",
    "End Rod",
    "End Stone",
    "End Stone Brick Slab",
    "End Stone Brick Stairs",
    "End Stone Brick Wall",
    "End Stone Bricks",
    "Ender Chest",
    "Ender Pearl",
    "Exposed Copper",
    "Exposed Cut Copper",
    "Exposed Cut Copper Slab",
    "Exposed Cut Copper Stairs",
    "Eye of Ender",
    "Feather",
    "Fermented Spider Eye",
    "Fern",
    "Fire Charge",
    "Fire Coral",
    "Fire Coral Block",
    "Fire Coral Fan",
    "Firework Rocket",
    "Firework Rocket Black",
    "Firework Rocket Blue",
    "Firework Rocket Brown",
    "Firework Rocket Cyan",
    "Firework Rocket Gray",
    "Firework Rocket Green",
    "Firework Rocket Light Blue",
    "Firework Rocket Light Gray",
    "Firework Rocket Lime",
    "Firework Rocket Magenta",
    "Firework Rocket Orange",
    "Firework Rocket Pink",
    "Firework Rocket Purple",
    "Firework Rocket Red",
    "Firework Rocket White",
    "Firework Rocket Yellow",
    "Firework Star",
    "Firework Star Black",
    "Firework Star Blue",
    "Firework Star Brown",
    "Firework Star Cyan",
    "Firework Star Gray",
    "Firework Star Green",
    "Firework Star Light Blue",
    "Firework Star Light Gray",
    "Firework Star Lime",
    "Firework Star Magenta",
    "Firework Star Orange",
    "Firework Star Pink",
    "Firework Star Purple",
    "Firework Star Red",
    "Firework Star White",
    "Firework Star Yellow",
    "Fishing Rod",
    "Fletching Table",
    "Flint",
    "Flint and Steel",
    "Flower Pot",
    "Flowering Azalea",
    "Flowering Azalea Leaves",
    "Furnace",
    "Ghast Tear",
    "Gilded Blackstone",
    "Glass",
    "Glass Bottle",
    "Glass Pane",
    "Glistering Melon Slice",
    "Glow Berries",
    "Glow Ink Sac",
    "Glow Item Frame",
    "Glow Lichen",
    "Glowstone",
    "Glowstone Dust",
    "Goat Horn",
    "Gold Ingot",
    "Gold Nugget",
    "Gold Ore",
    "Golden Apple",
    "Golden Axe",
    "Golden Boots",
    "Golden Carrot",
    "Golden Chestplate",
    "Golden Helmet",
    "Golden Hoe",
    "Golden Horse Armor",
    "Golden Leggings",
    "Golden Pickaxe",
    "Golden Shovel",
    "Golden Sword",
    "Granite",
    "Granite Slab",
    "Granite Stairs",
    "Granite Wall",
    "Grass",
    "Grass Block",
    "Gravel",
    "Gray Banner",
    "Gray Bed",
    "Gray Candle",
    "Gray Carpet",
    "Gray Concrete",
    "Gray Concrete Powder",
    "Gray Dye",
    "Gray Glazed Terracotta",
    "Gray Shulker Box",
    "Gray Stained Glass",
    "Gray Stained Glass Pane",
    "Gray Terracotta",
    "Gray Wool",
    "Green Banner",
    "Green Bed",
    "Green Candle",
    "Green Carpet",
    "Green Concrete",
    "Green Concrete Powder",
    "Green Dye",
    "Green Glazed Terracotta",
    "Green Shulker Box",
    "Green Stained Glass",
    "Green Stained Glass Pane",
    "Green Terracotta",
    "Green Wool",
    "Grindstone",
    "Guardian Head",
    "Gunpowder",
    "Hanging Roots",
    "Hardened Glass",
    "Hardened Glass Pane",
    "Hay Bale",
    "Heart of the Sea",
    "Heavy Weighted Pressure Plate",
    "Hoglin Banner Pattern",
    "Honey Block",
    "Honey Bottle",
    "Honeycomb",
    "Honeycomb Block",
    "Hopper",
    "Horn Coral",
    "Horn Coral Block",
    "Horn Coral Fan",
    "Horse Armor",
    "Ice",
    "Ice Bomb",
    "Infested Block",
    "Infested Chiseled Stone Bricks",
    "Infested Cobblestone",
    "Infested Cracked Stone Bricks",
    "Infested Deepslate",
    "Infested Deepslate Bricks",
    "Infested Deepslate Tiles",
    "Infested Mossy Stone Bricks",
    "Infested Stone",
    "Infested Stone Bricks",
    "Ink Sac",
    "Iron Axe",
    "Iron Bars",
    "Iron Boots",
    "Iron Chestplate",
    "Iron Door",
    "Iron Helmet",
    "Iron Hoe",
    "Iron Horse Armor",
    "Iron Ingot",
    "Iron Leggings",
    "Iron Nugget",
    "Iron Ore",
    "Iron Pickaxe",
    "Iron Shovel",
    "Iron Sword",
    "Iron Trapdoor",
    "Item Frame",
    "Jack o'Lantern",
    "Jigsaw Block",
    "Jukebox",
    "Jungle Boat",
    "Jungle Boat with Chest",
    "Jungle Button",
    "Jungle Door",
    "Jungle Fence",
    "Jungle Fence Gate",
    "Jungle Hanging Sign",
    "Jungle Leaves",
    "Jungle Log",
    "Jungle Planks",
    "Jungle Pressure Plate",
    "Jungle Sapling",
    "Jungle Sign",
    "Jungle Slab",
    "Jungle Stairs",
    "Jungle Trapdoor",
    "Jungle Wood",
    "Kelp",
    "Knowledge Book",
    "Ladder",
    "Lantern",
    "Lapis Lazuli",
    "Lapis Lazuli Block",
    "Lapis Lazuli Ore",
    "Large Amethyst Bud",
    "Large Fern",
    "Lava",
    "Lead",
    "Leather",
    "Leather Horse Armor",
    "Lectern",
    "Lever",
    "Light Block",
    "Light Blue Banner",
    "Light Blue Bed",
    "Light Blue Candle",
    "Light Blue Carpet",
    "Light Blue Concrete",
    "Light Blue Concrete Powder",
    "Light Blue Dye",
    "Light Blue Glazed Terracotta",
    "Light Blue Shulker Box",
    "Light Blue Stained Glass",
    "Light Blue Stained Glass Pane",
    "Light Blue Terracotta",
    "Light Blue Wool",
    "Light Gray Banner",
    "Light Gray Bed",
    "Light Gray Candle",
    "Light Gray Carpet",
    "Light Gray Concrete",
    "Light Gray Concrete Powder",
    "Light Gray Dye",
    "Light Gray Glazed Terracotta",
    "Light Gray Shulker Box",
    "Light Gray Stained Glass",
    "Light Gray Stained Glass Pane",
    "Light Gray Terracotta",
    "Light Gray Wool",
    "Light Weighted Pressure Plate",
    "Lightning Rod",
    "Lilac",
    "Lily Pad",
    "Lime Banner",
    "Lime Bed",
    "Lime Candle",
    "Lime Carpet",
    "Lime Concrete",
    "Lime Concrete Powder",
    "Lime Dye",
    "Lime Glazed Terracotta",
    "Lime Shulker Box",
    "Lime Stained Glass",
    "Lime Stained Glass Pane",
    "Lime Terracotta",
    "Lime Wool",
    "Lodestone",
    "Loom",
    "Magenta Banner",
    "Magenta Bed",
    "Magenta Candle",
    "Magenta Carpet",
    "Magenta Concrete",
    "Magenta Concrete Powder",
    "Magenta Dye",
    "Magenta Glazed Terracotta",
    "Magenta Shulker Box",
    "Magenta Stained Glass",
    "Magenta Stained Glass Pane",
    "Magenta Terracotta",
    "Magenta Wool",
    "Magnifying Glass",
    "Magma Block",
    "Magma Cream",
    "Magma Cube Spawn Egg",
    "Magnet",
    "Map",
    "Marrow Block",
    "Medium Amethyst Bud",
    "Melon",
    "Melon Seeds",
    "Melon Slice",
    "Milk",
    "Minecart",
    "Minecart with Chest",
    "Minecart with Command Block",
    "Minecart with Furnace",
    "Minecart with Hopper",
    "Minecart with Spawner",
    "Minecart with TNT",
    "Moist Wheat",
    "Mooshroom Banner Pattern",
    "Moss Block",
    "Moss Carpet",
    "Mossy Cobblestone",
    "Mossy Cobblestone Slab",
    "Mossy Cobblestone Stairs",
    "Mossy Cobblestone Wall",
    "Mossy Stone Brick Slab",
    "Mossy Stone Brick Stairs",
    "Mossy Stone Brick Wall",
    "Mossy Stone Bricks",
    "Mossy Stone Bricks Slab",
    "Mossy Stone Bricks Stairs",
    "Mossy Stone Bricks Wall",
    "Mounted Glow Item Frame",
    "Mounted Item Frame",
    "Mule Spawn Egg",
    "Mushroom Stem",
    "Mushroom Stew",
    "Music Disc",
    "Music Disc 11",
    "Music Disc 13",
    "Music Disc Blocks",
    "Music Disc Cat",
    "Music Disc Chirp",
    "Music Disc Far",
    "Music Disc Mall",
    "Music Disc Mellohi",
    "Music Disc Pigstep",
    "Music Disc Stal",
    "Music Disc Strad",
    "Music Disc Wait",
    "Music Disc Ward",
    "Mycelium",
    "Nautilus Shell",
    "Nether Brick",
    "Nether Brick Fence",
    "Nether Brick Slab",
    "Nether Brick Stairs",
    "Nether Brick Wall",
    "Nether Bricks",
    "Nether Gold Ore",
    "Nether Mushroom",
    "Nether Quartz Ore",
    "Nether Sprouts",
    "Nether Star",
    "Nether Wart",
    "Nether Wart Block",
    "Netherite Axe",
    "Netherite Block",
    "Netherite Boots",
    "Netherite Chestplate",
    "Netherite Helmet",
    "Netherite Hoe",
    "Netherite Ingot",
    "Netherite Leggings",
    "Netherite Pickaxe",
    "Netherite Scrap",
    "Netherite Shovel",
    "Netherite Sword",
    "Netherrack",
    "Netherreactor Core",
    "Note Block",
    "Oak Boat",
    "Oak Boat with Chest",
    "Oak Button",
    "Oak Door",
    "Oak Fence",
    "Oak Fence Gate",
    "Oak Leaves",
    "Oak Log",
    "Oak Planks",
    "Oak Pressure Plate",
    "Oak Sapling",
    "Oak Sign",
    "Oak Slab",
    "Oak Stairs",
    "Oak Trapdoor",
    "Oak Wood",
    "Observer",
    "Obsidian",
    "Ocelot Banner Pattern",
    "Orange Banner",
    "Orange Bed",
    "Orange Candle",
    "Orange Carpet",
    "Orange Concrete",
    "Orange Concrete Powder",
    "Orange Dye",
    "Orange Glazed Terracotta",
    "Orange Shulker Box",
    "Orange Stained Glass",
    "Orange Stained Glass Pane",
    "Orange Terracotta",
    "Orange Tulip",
    "Orange Wool",
    "Oxeye Daisy",
    "Oxeye Daisy Seeds",
    "Oxidized Copper",
    "Oxidized Cut Copper",
    "Oxidized Cut Copper Slab",
    "Oxidized Cut Copper Stairs",
    "Packed Ice",
    "Painting",
    "Panda Banner Pattern",
    "Paper",
    "Parrot Banner Pattern",
    "Peony",
    "Petrified Oak Slab",
    "Phantom Membrane",
    "Piglin Banner Pattern",
    "Piglin Brute Banner Pattern",
    "Piglin Spawn Egg",
    "Piglin Brute Spawn Egg",
    "Pillager Spawn Egg",
    "Pink Banner",
    "Pink Bed",
    "Pink Candle",
    "Pink Carpet",
    "Pink Concrete",
    "Pink Concrete Powder",
    "Pink Dye",
    "Pink Glazed Terracotta",
    "Pink Shulker Box",
    "Pink Stained Glass",
    "Pink Stained Glass Pane",
    "Pink Terracotta",
    "Pink Tulip",
    "Pink Wool",
    "Piston",
    "Player Head",
    "Podzol",
    "Poisonous Potato",
    "Polar Bear Banner Pattern",
    "Polished Andesite",
    "Polished Andesite Slab",
    "Polished Andesite Stairs",
    "Polished Basalt",
    "Polished Basalt Slab",
    "Polished Basalt Stairs",
    "Polished Blackstone",
    "Polished Blackstone Brick Slab",
    "Polished Blackstone Brick Stairs",
    "Polished Blackstone Brick Wall",
    "Polished Blackstone Bricks",
    "Polished Blackstone Button",
    "Polished Blackstone Pressure Plate",
    "Polished Blackstone Slab",
    "Polished Blackstone Stairs",
    "Polished Blackstone Wall",
    "Polished Deepslate",
    "Polished Deepslate Slab",
    "Polished Deepslate Stairs",
    "Polished Deepslate Wall",
    "Polished Diorite",
    "Polished Diorite Slab",
    "Polished Diorite Stairs",
    "Polished Granite",
    "Polished Granite Slab",
    "Polished Granite Stairs",
    "Popped Chorus Fruit",
    "Poppy",
    "Porkchop",
    "Potato",
    "Potion",
    "Powder Snow",
    "Powder Snow Bucket",
    "Powered Rail",
    "Prismarine",
    "Prismarine Brick Slab",
    "Prismarine Brick Stairs",
    "Prismarine Bricks",
    "Prismarine Crystals",
    "Prismarine Shard",
    "Prismarine Slab",
    "Prismarine Stairs",
    "Prismarine Wall",
    "Pufferfish",
    "Pumpkin",
    "Pumpkin Pie",
    "Pumpkin Seeds",
    "Purple Banner",
    "Purple Bed",
    "Purple Candle",
    "Purple Carpet",
    "Purple Concrete",
    "Purple Concrete Powder",
    "Purple Dye",
    "Purple Glazed Terracotta",
    "Purple Shulker Box",
    "Purple Stained Glass",
    "Purple Stained Glass Pane",
    "Purple Terracotta",
    "Purple Wool",
    "Purpur Block",
    "Purpur Pillar",
    "Purpur Slab",
    "Purpur Stairs",
    "Quartz",
    "Quartz Block",
    "Quartz Bricks",
    "Quartz Pillar",
    "Quartz Slab",
    "Quartz Stairs",
    "Rabbit",
    "Rabbit's Foot",
    "Rabbit Hide",
    "Rabbit Stew",
    "Rail",
    "Ravager Spawn Egg",
    "Raw Beef",
    "Raw Chicken",
    "Raw Cod",
    "Raw Copper",
    "Raw Copper Block",
    "Raw Gold",
    "Raw Gold Block",
    "Raw Iron",
    "Raw Iron Block",
    "Raw Mutton",
    "Raw Porkchop",
    "Raw Rabbit",
    "Raw Salmon",
    "Red Banner",
    "Red Bed",
    "Red Candle",
    "Red Carpet",
    "Red Concrete",
    "Red Concrete Powder",
    "Red Dye",
    "Red Glazed Terracotta",
    "Red Mushroom",
    "Red Mushroom Block",
    "Red Nether Brick",
    "Red Nether Brick Slab",
    "Red Nether Brick Stairs",
    "Red Nether Brick Wall",
    "Red Sand",
    "Red Sandstone",
    "Red Sandstone Slab",
    "Red Sandstone Stairs",
    "Red Sandstone Wall",
    "Red Shulker Box",
    "Red Stained Glass",
    "Red Stained Glass Pane",
    "Red Terracotta",
    "Red Tulip",
    "Red Wool",
    "Redstone",
    "Redstone Block",
    "Redstone Comparator",
    "Redstone Lamp",
    "Redstone Ore",
    "Redstone Repeater",
    "Redstone Torch",
    "Redstone Wire",
    "Repeater",
    "Respawn Anchor",
    "Rose Bush",
    "Rotten Flesh",
    "Saddle",
    "Salmon",
    "Sand",
    "Sandstone",
    "Sandstone Slab",
    "Sandstone Stairs",
    "Sandstone Wall",
    "Scaffolding",
    "Sculk Block",
    "Scute",
    "Sea Lantern",
    "Sea Pickle",
    "Seagrass",
    "Shears",
    "Sheep Spawn Egg",
    "Shield",
    "Shroomlight",
    "Shulker Box",
    "Shulker Shell",
    "Silverfish Spawn Egg",
    "Silverfish Stone",
    "Silverfish Stone Slab",
    "Silverfish Stone Stairs",
    "Silverfish Stone Wall",
    "Skeleton Horse Spawn Egg",
    "Skeleton Skull",
    "Skeleton Spawn Egg",
    "Skull",
    "Slime Ball",
    "Slime Block",
    "Slime Spawn Egg",
    "Small Amethyst Bud",
    "Small Dripleaf",
    "Smithing Table",
    "Smoker",
    "Smooth Basalt",
    "Smooth Quartz",
    "Smooth Quartz Block",
    "Smooth Quartz Slab",
    "Smooth Quartz Stairs",
    "Smooth Red Sandstone",
    "Smooth Red Sandstone Slab",
    "Smooth Red Sandstone Stairs",
    "Smooth Sandstone",
    "Smooth Sandstone Slab",
    "Smooth Sandstone Stairs",
    "Smooth Stone",
    "Smooth Stone Slab",
    "Snow",
    "Snow Block",
    "Soul Campfire",
    "Soul Lantern",
    "Soul Sand",
    "Soul Soil",
    "Soul Torch",
    "Spawner",
    "Spectral Arrow",
    "Spider Eye",
    "Spider Spawn Egg",
    "Splash Potion",
    "Sponge",
    "Spore Blossom",
    "Spruce Boat",
    "Spruce Boat with Chest",
    "Spruce Button",
    "Spruce Door",
    "Spruce Fence",
    "Spruce Fence Gate",
    "Spruce Hanging Sign",
    "Spruce Leaves",
    "Spruce Log",
    "Spruce Planks",
    "Spruce Pressure Plate",
    "Spruce Sapling",
    "Spruce Sign",
    "Spruce Slab",
    "Spruce Stairs",
    "Spruce Trapdoor",
    "Spruce Wood",
    "Spyglass",
    "Squid Spawn Egg",
    "Stackable Snow Bucket",
    "Stick",
    "Sticky Piston",
    "Stone",
    "Stone Axe",
    "Stone Brick Slab",
    "Stone Brick Stairs",
    "Stone Brick Wall",
    "Stone Bricks",
    "Stone Bricks Slab",
    "Stone Bricks Stairs",
    "Stone Bricks Wall",
    "Stone Button",
    "Stone Hoe",
    "Stone Pickaxe",
    "Stone Pressure Plate",
    "Stone Shovel",
    "Stone Slab",
    "Stone Stairs",
    "Stonecutter",
    "Stray Spawn Egg",
    "Strider Spawn Egg",
    "String",
    "Stripped Acacia Log",
    "Stripped Acacia Wood",
    "Stripped Birch Log",
    "Stripped Birch Wood",
    "Stripped Crimson Hyphae",
    "Stripped Crimson Stem",
    "Stripped Dark Oak Log",
    "Stripped Dark Oak Wood",
    "Stripped Jungle Log",
    "Stripped Jungle Wood",
    "Stripped Oak Log",
    "Stripped Oak Wood",
    "Stripped Spruce Log",
    "Stripped Spruce Wood",
    "Stripped Warped Hyphae",
    "Stripped Warped Stem",
    "Stripped Wood",
    "Structure Block",
    "Structure Void",
    "Sugarcane",
    "Sugar",
    "Sunflower",
    "Suspicious Stew",
    "Sweet Berries",
    "Sweet Berry Bush",
    "Tall Grass",
    "Tall Seagrass",
    "Target",
    "Tinted Glass",
    "Tipped Arrow",
    "Tnt",
    "Tnt Minecart",
    "Totem of Undying",
    "Trapped Chest",
    "Trident",
    "Tripwire",
    "Tripwire Hook",
    "Tropical Fish",
    "Tropical Fish Bucket",
    "Tuff",
    "Turtle Banner Pattern",
    "Turtle Egg",
    "Turtle Helmet",
    "Turtle Shell",
    "Twisting Vines",
    "Vex Spawn Egg",
    "Villager Spawn Egg",
    "Vindicator Spawn Egg",
    "Vine",
    "Wandering Trader Spawn Egg",
    "Warped Button",
    "Warped Door",
    "Warped Fence",
    "Warped Fence Gate",
    "Warped Fungus",
    "Warped Fungus on a Stick",
    "Warped Hanging Roots",
    "Warped Hyphae",
    "Warped Nylium",
    "Warped Planks",
    "Warped Pressure Plate",
    "Warped Roots",
    "Warped Sign",
    "Warped Slab",
    "Warped Stairs",
    "Warped Stem",
    "Warped Trapdoor",
    "Warped Wart Block",
    "Warped Wood",
    "Water",
    "Water Bucket",
    "Waxed Block",
    "Waxed Copper",
    "Waxed Cut Copper",
    "Waxed Cut Copper Slab",
    "Waxed Cut Copper Stairs",
    "Waxed Exposed Copper",
    "Waxed Exposed Cut Copper",
    "Waxed Exposed Cut Copper Slab",
    "Waxed Exposed Cut Copper Stairs",
    "Waxed Oxidized Copper",
    "Waxed Oxidized Cut Copper",
    "Waxed Oxidized Cut Copper Slab",
    "Waxed Oxidized Cut Copper Stairs",
    "Weathered Copper",
    "Weathered Cut Copper",
    "Weathered Cut Copper Slab",
    "Weathered Cut Copper Stairs",
    "Wet Sponge",
    "Wheat",
    "Wheat Seeds",
    "White Banner",
    "White Bed",
    "White Candle",
    "White Carpet",
    "White Concrete",
    "White Concrete Powder",
    "White Dye",
    "White Glazed Terracotta",
    "White Shulker Box",
    "White Stained Glass",
    "White Stained Glass Pane",
    "White Terracotta",
    "White Tulip",
    "White Wool",
    "Witch Spawn Egg",
    "Wither Rose",
    "Wither Skeleton Skull",
    "Wither Skeleton Spawn Egg",
    "Wolf Spawn Egg",
    "Wooden Axe",
    "Wooden Hoe",
    "Wooden Pickaxe",
    "Wooden Shovel",
    "Wooden Sword",
    "Wool",
    "Writable Book",
    "Written Book",
    "Yellow Banner",
    "Yellow Bed",
    "Yellow Candle",
    "Yellow Carpet",
    "Yellow Concrete",
    "Yellow Concrete Powder",
    "Yellow Dye",
    "Yellow Flower",
    "Yellow Glazed Terracotta",
    "Yellow Shulker Box",
    "Yellow Stained Glass",
    "Yellow Stained Glass Pane",
    "Yellow Terracotta",
    "Yellow Wool",
    "Zoglin Spawn Egg",
    "Zombie Banner Pattern",
    "Zombie Head",
    "Zombie Horse Spawn Egg",
    "Zombie Pigman Spawn Egg",
    "Zombie Spawn Egg",
    "Zombie Villager Spawn Egg",
    "Zombified Piglin Spawn Egg"
    };

    string[] potions = new string[]
    {
    "Water Bottle",
    "Awkward Potion",
    "Mundane Potion",
    "Thick Potion",
    "Potion of Regeneration",
    "Potion of Regeneration +",
    "Potion of Regeneration II",
    "Potion of Swiftness",
    "Potion of Swiftness +",
    "Potion of Swiftness II",
    "Potion of Fire Resistance",
    "Potion of Fire Resistance +",
    "Potion of Healing",
    "Potion of Healing II",
    "Potion of Night Vision",
    "Potion of Night Vision +",
    "Potion of Strength",
    "Potion of Strength +",
    "Potion of Strength II",
    "Potion of Leaping",
    "Potion of Leaping +",
    "Potion of Leaping II",
    "Potion of Water Breathing",
    "Potion of Water Breathing +",
    "Potion of Invisibility",
    "Potion of Invisibility +",
    "Potion of Slow Falling",
    "Potion of Slow Falling +",
    "Potion of Poison",
    "Potion of Poison +",
    "Potion of Poison II",
    "Potion of Weakness",
    "Potion of Weakness +",
    "Potion of Slowness",
    "Potion of Slowness +",
    "Potion of Slowness IV",
    "Potion of Harming",
    "Potion of Harming II",
    "Potion of the Turtle Master",
    "Potion of the Turtle Master +",
    "Potion of the Turtle Master II",
    "Splash Potions",
    "Splash Water Bottle",
    "Splash Awkward Potion",
    "Splash Mundane Potion",
    "Splash Thick Potion",
    "Splash Potion of Regeneration",
    "Splash Potion of Regeneration +",
    "Splash Potion of Regeneration II",
    "Splash Potion of Swiftness",
    "Splash Potion of Swiftness +",
    "Splash Potion of Swiftness II",
    "Splash Potion of Fire Resistance",
    "Splash Potion of Fire Resistance +",
    "Splash Potion of Healing",
    "Splash Potion of Healing II",
    "Splash Potion of Night Vision",
    "Splash Potion of Night Vision +",
    "Splash Potion of Strength",
    "Splash Potion of Strength +",
    "Splash Potion of Strength II",
    "Splash Potion of Leaping",
    "Splash Potion of Leaping +",
    "Splash Potion of Leaping II",
    "Splash Potion of Water Breathing",
    "Splash Potion of Water Breathing +",
    "Splash Potion of Invisibility",
    "Splash Potion of Invisibility +",
    "Splash Potion of Slow Falling",
    "Splash Potion of Slow Falling +",
    "Splash Potion of Poison",
    "Splash Potion of Poison +",
    "Splash Potion of Poison II",
    "Splash Potion of Weakness",
    "Splash Potion of Weakness +",
    "Splash Potion of Slowness",
    "Splash Potion of Slowness +",
    "Splash Potion of Slowness IV",
    "Splash Potion of Harming",
    "Splash Potion of Harming II",
    "Splash Potion of the Turtle Master",
    "Splash Potion of the Turtle Master +",
    "Splash Potion of the Turtle Master II",
    "Lingering Potions",
    "Lingering Water Bottle",
    "Lingering Awkward Potion",
    "Lingering Mundane Potion",
    "Lingering Thick Potion",
    "Lingering Potion of Regeneration",
    "Lingering Potion of Regeneration +",
    "Lingering Potion of Regeneration II",
    "Lingering Potion of Swiftness",
    "Lingering Potion of Swiftness +",
    "Lingering Potion of Swiftness II",
    "Lingering Potion of Fire Resistance",
    "Lingering Potion of Fire Resistance +",
    "Lingering Potion of Healing",
    "Lingering Potion of Healing II",
    "Lingering Potion of Night Vision",
    "Lingering Potion of Night Vision +",
    "Lingering Potion of Strength",
    "Lingering Potion of Strength +",
    "Lingering Potion of Strength II",
    "Lingering Potion of Leaping",
    "Lingering Potion of Leaping +",
    "Lingering Potion of Leaping II",
    "Lingering Potion of Water Breathing",
    "Lingering Potion of Water Breathing +",
    "Lingering Potion of Invisibility",
    "Lingering Potion of Invisibility +",
    "Lingering Potion of Slow Falling",
    "Lingering Potion of Slow Falling +",
    "Lingering Potion of Poison",
    "Lingering Potion of Poison +",
    "Lingering Potion of Poison II",
    "Lingering Potion of Weakness",
    "Lingering Potion of Weakness +",
    "Lingering Potion of Slowness",
    "Lingering Potion of Slowness +",
    "Lingering Potion of Slowness IV",
    "Lingering Potion of Harming",
    "Lingering Potion of Harming II",
    "Lingering Potion of the Turtle Master",
    "Lingering Potion of the Turtle Master +",
    "Lingering Potion of the Turtle Master II"
    };

    string[] enchantments = new string[]
    {
    "Aqua Affinity I",
    "Bane of Arthropods V",
    "Blast Protection IV",
    "Channeling I",
    "Curse of Binding I",
    "Curse of Vanishing I",
    "Depth Strider III",
    "Efficiency V",
    "Feather Falling IV",
    "Fire Aspect II",
    "Fire Protection IV",
    "Flame I",
    "Fortune III",
    "Frost Walker II",
    "Impaling V",
    "Infinity I",
    "Knockback II",
    "Looting III",
    "Loyalty III",
    "Luck of the Sea III",
    "Lure III",
    "Mending I",
    "Multishot I",
    "Piercing IV",
    "Power V",
    "Projectile Protection IV",
    "Protection IV",
    "Punch II",
    "Quick Charge III",
    "Respiration III",
    "Riptide III",
    "Sharpness V",
    "Silk Touch I",
    "Smite V",
    "Soul Speed III",
    "Swift Sneak III",
    "Thorns III",
    "Unbreaking III"
    };
    public static Items Instance { get; set; }
    public void ShowRandomText()
    {
        // Select a random item from the list
        string randomItem = item[Random.Range(0, item.Length)];
        // Display the random item
        displayText.text = "Get: " + Random.Range(1, 30) + " " + randomItem;
    }
    public void PotionsText()
    {
        // Select a random item from the list
        string randomPotions = potions[Random.Range(0, potions.Length)];
        // Display the random item
        displayText.text = "Get: " + Random.Range(1, 5) + " " + randomPotions;
    }
    public void EnchantsText()
    {
        // Select a random item from the list
        string randomEnchantments = enchantments[Random.Range(0, enchantments.Length)];
        // Display the random item
        displayText.text = "Use enchantments" + " " + randomEnchantments + " on any equipment";
    }
}
